version: "3.9"

services:
  rest-api-dev:
    build:
      context: .
      target: development
    container_name: rest-api-dev
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=rest-api
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - mongo
    networks:
      - default

  mongo:
    image: mongo:4.2.8
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - default

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - "8089:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - default

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped
    networks:
      - default

  web:
    image: nginx:mainline-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - rest-api-dev
    networks:
      - default

networks:
  default:
    driver: bridge
